


// Example of using data types
console.log("----- Data Types Examples -----");
console.log("Primitive Data Types:");
let name = "Ayush"; // String
let age = 21; // Number
let isStudent = true; // Boolean
let x; // Undefined
let y = null; // Null
console.log("Name:", name, "Data Type", typeof name);// Output: string
console.log("Age:", age, "Data Type", typeof age);// Output: number
console.log("Is Student:", isStudent, "Data Type", typeof isStudent);// Output: boolean
console.log("X:", x, "Data Type", typeof x);// Output: undefined
console.log("Y:", y, "Data Type", typeof y);// Output: object

console.log("-----");
console.log("Non-Primitive Data Types:");
let person = { name: "Ayush", age: 21 }; // Object
let numbers = [1, 2, 3, 4, 5]; // Array
function greet() { // Function
    return "Hello!";
}
console.log("Person:", person, "Data Type", typeof person);// Output: object
console.log("Numbers:", numbers, "Data Type", typeof numbers);// Output: object
console.log("Greet Function:", greet, "Data Type", typeof greet);// Output:
console.log("Greet Function Call:", greet(), "Data Type", typeof greet());// Output: string
console.log("----- End of Examples -----");

console.log("");
console.log("👨‍💻 Created by Ayush Narware");
console.log("Thank you for visiting! 👋");
console.log("Happy Coding! 😊");
